name: Check JSON Changes
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install requests

      - name: Check JSON changes
        id: check_json
        env:
          NOTIFY_EMAIL: ${{ secrets.EMAIL_USERNAME }}
          JSON_URL_1: https://oia.nycu.edu.tw/oia/en/app/openData/data/list?module=nycu0016&mserno=07d5a12a-fbc5-492a-ba47-be3b2ff68813&type=json&id=807
          JSON_URL_2: https://oia.nycu.edu.tw/oia/en/app/openData/data/list?module=nycu0017&mserno=2f9f7ba1-83f8-4ae2-8154-9ef23ded61a2&type=json&id=814
        run: |
          output=$(python .github/scripts/check_json.py)
          echo "::set-output name=changes::$output"

      - name: Send email
        if: steps.check_json.outputs.changes != ''
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Updates in NYCU OIA Jobs
          body: ${{ steps.check_json.outputs.changes }}
          to: renega99@gmail.com
          from: GitHub Action
